#!/usr/bin/env python3
"""
Generate CONFORMANCE.md from /guard/audit/checks endpoint.
Single source of truth: CHECK_REGISTRY in skill.ts.

Usage: python3 gen_conformance.py
"""
import json
import sys
from pathlib import Path
from datetime import datetime
from urllib.request import urlopen, Request
from urllib.error import URLError

API = 'https://api.moltrust.ch/guard/audit/checks'

OUTPUTS = [
    Path.home() / 'moltrust-protocol' / 'docs' / 'CONFORMANCE.md',
    Path('/var/www/html/CONFORMANCE.md'),
]

SEVERITY_EMOJI = {
    'critical': '🔴',
    'high': '🟠',
    'medium': '🟡',
    'low': '🟢',
}


def fetch_checks() -> dict:
    req = Request(API, headers={'User-Agent': 'gen_conformance/1.0'})
    try:
        resp = urlopen(req, timeout=10)
        return json.loads(resp.read())
    except URLError as e:
        print(f"ERROR: Could not reach {API}: {e}")
        sys.exit(1)


def generate_md(data: dict) -> str:
    check_count = data['check_count']
    checksum = data['checksum']
    generated = data['generated_at']

    hard_fail_checks = [c for c in data['checks'] if c.get('hard_fail')]
    with_cwe = [c for c in data['checks'] if c.get('cwe_id')]

    md = f"""# MolTrust Skill Audit — Conformance

**Version:** {data['version']}
**Check Count:** {check_count}
**Registry Checksum:** `{checksum}`
**Generated:** {generated}
**Source API:** {API}

<!-- AUTO-GENERATED by moltguard/scripts/gen_conformance.py — DO NOT EDIT MANUALLY -->
<!-- To regenerate: python3 ~/moltguard/scripts/gen_conformance.py -->

## Overview

The MolTrust Skill Audit evaluates AI agent skills against {check_count} checks across multiple security and compliance dimensions. Findings result in score deductions; one check category can trigger a hard fail where no Verifiable Credential is issued.

- **Total checks:** {check_count}
- **Hard-fail checks:** {len(hard_fail_checks)} ({', '.join(c['id'] for c in hard_fail_checks)})
- **With CWE mapping:** {len(with_cwe)} of {check_count}
- **Audit output:** Score 0-100, list of findings with line-level references
- **Passing score:** 70 (required for VerifiedSkillCredential issuance)

## Check Details

"""

    for severity in ('critical', 'high', 'medium', 'low'):
        group = [c for c in data['checks'] if c['severity'] == severity]
        if not group:
            continue
        emoji = SEVERITY_EMOJI[severity]
        md += f"### {emoji} {severity.title()} Severity\n\n"

        for check in group:
            hard_fail_note = " **— HARD FAIL**" if check.get('hard_fail') else ""
            md += f"#### `{check['id']}` — {check['display_name']}{hard_fail_note}\n\n"
            md += f"- **Severity:** {check['severity']}\n"
            md += f"- **Score deduction:** -{check['deduction']} points\n"
            md += f"- **Check type:** {check['check_type']}\n"
            if check.get('pattern_count'):
                md += f"- **Patterns:** {check['pattern_count']} regex patterns\n"
            if check.get('cwe_id'):
                md += f"- **CWE:** [{check['cwe_id']}]({check['cwe_url']}) — {check['cwe_name']}\n"
            else:
                md += f"- **CWE:** Not applicable (structural or protocol check)\n"
            md += f"\n{check['description']}\n\n"

    md += f"""---

## Scoring

| Grade | Score Range |
|-------|------------|
| A     | 90 - 100   |
| B     | 80 - 89    |
| C     | 70 - 79    |
| D     | 50 - 69    |
| F     | 0 - 49     |

- Minimum score for VerifiedSkillCredential issuance: **70**
- Hard fail checks force score to **0** regardless of other findings

## Summary Table

| Check | Severity | Deduction | Hard Fail | CWE |
|-------|----------|-----------|-----------|-----|
"""

    for c in data['checks']:
        cwe = f"[{c['cwe_id']}]({c['cwe_url']})" if c.get('cwe_id') else "—"
        hf = "Yes" if c.get('hard_fail') else "No"
        md += f"| `{c['id']}` | {c['severity']} | -{c['deduction']} | {hf} | {cwe} |\n"

    md += f"""
## Integrity

This document is auto-generated from the live API endpoint `{API}`.

**Verification:**

```bash
# Verify registry checksum matches this document
curl -s {API.replace('/checks', '/version')} | jq .checksum
# Expected: "{checksum}"

# Full check registry
curl -s {API} | jq .
```

**Regenerate:**

```bash
python3 ~/moltguard/scripts/gen_conformance.py
```

---

*MolTrust / CryptoKRI GmbH, Zurich*
*Registry checksum: `{checksum}`*
"""

    return md


def main():
    print(f"Fetching check registry from {API}...")
    data = fetch_checks()
    print(f"  check_count: {data['check_count']}")
    print(f"  checksum: {data['checksum']}")

    md = generate_md(data)

    written = 0
    for path in OUTPUTS:
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(md, encoding='utf-8')
            print(f"  Written: {path}")
            written += 1
        except PermissionError:
            print(f"  SKIP (permission denied): {path}")
            print(f"  Run: sudo cp /tmp/CONFORMANCE.md {path}")
        except Exception as e:
            print(f"  ERROR writing {path}: {e}")

    if written > 0:
        print(f"\nDone. {written} file(s) written.")
    else:
        # Write to /tmp as fallback
        fallback = Path('/tmp/CONFORMANCE.md')
        fallback.write_text(md, encoding='utf-8')
        print(f"\nFallback written to {fallback}")

    return 0


if __name__ == '__main__':
    sys.exit(main())
